apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: avkTerraformTest
  title: Terraform integration
  description: Test integration with terraform
  tags:
    - terraform
    - deployment
    - provisioning
spec:
  owner: avk@sitecore.net
  type: component
  parameters:
    - title: Component configuration
      required:
#        - workspace_name
#        - organization_name
#        - execution_mode
#        - auto_apply
#        - speculative_enabled
#        - working_directory
#        - identifier
#        - branch
#        - ingress_submodules
#        - oauth_token_id
#        - environment
#        - component
#        - branch
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
#        workspace_name:
#          title: Name
#          type: string
#          description: Unique name of the workspace
#          ui:field: EntityNamePicker
 #       organization_name:
 #         title: Organization name
 #         type: string
 #         description: Name of the organization
 #       execution_mode:
 #         title: Execution Mode
 #         type: string
 #         description: Execution Mode
 #       auto_apply:
 #         title: Auto apply deployment
 #         description: Auto apply deployment
 #         type: boolean
 #         default: false
 #       speculative_enabled:
 #         title: Speculative Enabled
 #         description: Speculative Enabled
 #         type: boolean
 #         default: true
 #       working_directory:
 #         title: Working Directory
 #         type: string
 #         description: Working Directory
 #       identifier:
 #         title: Identifier
 #         type: string
 #         description: identifier
 #       branch:
 #         title: Branch
 #         type: string
 #         description: Branch
 #       ingress_submodules:
 #         title: Ingress Submodules
 #         description: Ingress Submodules
 #         type: boolean
 #         default: false
 #       oauth_token_id:
 #         title: Oauth Token Id
 #         type: string
 #         description: Oauth Token Id
 #       environment:
 #         title: Environment
 #         type: string
 #         description: Environment
 #       component:
 #         title: Component
 #         type: string
 #         description: Component
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
        branchName:
          title: Name of the branch
          type: string
        prTitle:
          title: Title of PR
          type: string
  steps:
#    - id: template
#      name: Fetch Skeleton + Template
#      action: fetch:template
#      input:
#        url: https://github.com/alexv80/RepoForImport
#        copyWithoutRender:
#          - .github/workflows/*
#        values:
#          component_id: ${{ parameters.component_id }}
#          description: ${{ parameters.description }}
#          destination: ${{ parameters.repoUrl | parseRepoUrl }}
#          owner: ${{ parameters.owner }}

    - id: pullRequest
      name: Create pull request
      action: publish:github:pull-request
      input:
        allowedHosts: ["github.com"]
        description: This is ${{ parameters.workspace_name }}
        repoUrl: ${{ parameters.repoUrl }}
        branchName: ${{ parameters.branchName }}
        title: ${{ parameters.prTitle }}

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
