apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: avkTerraformTest
  title: Terraform integration
  description: Test integration with terraform
  tags:
    - terraform
    - deployment
    - provisioning
spec:
  owner: avk@sitecore.net
  type: component
  parameters:
    - title: Component information
      required:
        - workspace_name
        - organization_name
        - execution_mode
        - auto_apply
        - speculative_enabled
        - working_directory
        - identifier
        - branch
        - ingress_submodules
        - oauth_token_id
        - environment
        - component
        - branch
      properties:
        workspace_name:
          title: Name
          type: string
          description: Unique name of the workspace
          ui:field: EntityNamePicker
        organization_name:
          title: Organization name
          type: string
          description: Name of the organization
        execution_mode:
          title: Execution Mode
          type: string
          description: Execution Mode
        auto_apply:
          title: Auto apply deployment
          description: Auto apply deployment
          type: boolean
          default: false
        speculative_enabled:
          title: Speculative Enabled
          description: Speculative Enabled
          type: boolean
          default: true
        working_directory:
          title: Working Directory
          type: string
          description: Working Directory
        identifier:
          title: Identifier
          type: string
          description: identifier
        branch:
          title: Branch
          type: string
          description: Branch
        ingress_submodules:
          title: Ingress Submodules
          description: Ingress Submodules
          type: boolean
          default: true
        oauth_token_id:
          title: Oauth Token Id
          type: string
          description: Oauth Token Id
        environment:
          title: Environment
          type: string
          description: Environment
        component:
          title: Component
          type: string
          description: Component
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
